#!/bin/bash

folder="/home/toby/.config/rofi/launchers/type-$1/"  # Specify the folder path

# Loop through the files in the folder
for file in "$folder"/*.rasi; do
    # Check if the file exists and is readable
    if [[ -f "$file" && -r "$file" ]]; then
        # Edit the file using sed
        sed -i 's/fullscreen:[[:space:]]\+false;/fullscreen:                  true;/g' "$file"
        echo "Edited $file"
    fi
done
