;;; exwm-autoloads.el --- automatically extracted autoloads (do not edit)   -*- lexical-binding: t -*-
;; Generated by the `loaddefs-generate' function.

;; This file is part of GNU Emacs.

;;; Code:

(add-to-list 'load-path (or (and load-file-name (directory-file-name (file-name-directory load-file-name))) (car load-path)))



;;; Generated autoloads from exwm.el

(autoload 'exwm-restart "exwm" "\
Restart EXWM." t)
(autoload 'exwm-init "exwm" "\
Initialize EXWM.

(fn &optional FRAME)" t)
(autoload 'exwm-exit "exwm" "\
Exit EXWM." t)
(autoload 'exwm-enable "exwm" "\
Enable/Disable EXWM.

(fn &optional UNDO)")
(register-definition-prefixes "exwm" '("exwm-"))


;;; Generated autoloads from exwm-cm.el

(register-definition-prefixes "exwm-cm" '("exwm-cm-"))


;;; Generated autoloads from exwm-config.el

(register-definition-prefixes "exwm-config" '("exwm-config-"))


;;; Generated autoloads from exwm-core.el

(register-definition-prefixes "exwm-core" '("exwm-"))


;;; Generated autoloads from exwm-floating.el

(autoload 'exwm-floating-toggle-floating "exwm-floating" "\
Toggle the current window between floating and non-floating states." t)
(autoload 'exwm-floating-hide "exwm-floating" "\
Hide the current floating X window (which would show again when selected)." t)
(register-definition-prefixes "exwm-floating" '("exwm-floating-"))


;;; Generated autoloads from exwm-input.el

(autoload 'exwm-input-set-key "exwm-input" "\
Set a global key binding.

The new key binding only takes effect in real time when this command is
called interactively, and is lost when this session ends unless it's
specifically saved in the Customize interface for `exwm-input-global-keys'.

In configuration you should customize or set `exwm-input-global-keys'
instead.

(fn KEY COMMAND)" t)
(autoload 'exwm-input-grab-keyboard "exwm-input" "\
Switch to line-mode.

(fn &optional ID)" t)
(autoload 'exwm-input-release-keyboard "exwm-input" "\
Switch to char-mode.

(fn &optional ID)" t)
(autoload 'exwm-input-toggle-keyboard "exwm-input" "\
Toggle between 'line-mode' and 'char-mode'.

(fn &optional ID)" t)
(autoload 'exwm-input-send-next-key "exwm-input" "\
Send next key to client window.

EXWM will prompt for the key to send.  This command can be prefixed to send
multiple keys.  If END-KEY is non-nil, stop sending keys if it's pressed.

(fn TIMES &optional END-KEY)" t)
(autoload 'exwm-input-set-simulation-key "exwm-input" "\
Set a simulation key.

The simulation key takes effect in real time, but is lost when this session
ends unless it's specifically saved in the Customize interface for
`exwm-input-simulation-keys'.

(fn ORIGINAL-KEY SIMULATED-KEY)" t)
(autoload 'exwm-input-send-simulation-key "exwm-input" "\
Fake a key event according to the last input key sequence.

(fn TIMES)" t)
(autoload 'exwm-input-invoke-factory "exwm-input" "\
Make a command that invokes KEYS when called.

One use is to access the keymap bound to KEYS (as prefix keys) in char-mode.

(fn KEYS)" nil t)
(register-definition-prefixes "exwm-input" '("exwm-input-"))


;;; Generated autoloads from exwm-layout.el

(autoload 'exwm-layout-set-fullscreen "exwm-layout" "\
Make window ID fullscreen.

(fn &optional ID)" t)
(autoload 'exwm-layout-unset-fullscreen "exwm-layout" "\
Restore window from fullscreen state.

(fn &optional ID)" t)
(autoload 'exwm-layout-toggle-fullscreen "exwm-layout" "\
Toggle fullscreen mode.

(fn &optional ID)" t)
(autoload 'exwm-layout-enlarge-window "exwm-layout" "\
Make the selected window DELTA pixels taller.

If no argument is given, make the selected window one pixel taller.  If the
optional argument HORIZONTAL is non-nil, make selected window DELTA pixels
wider.  If DELTA is negative, shrink selected window by -DELTA pixels.

Normal hints are checked and regarded if the selected window is displaying an
`exwm-mode' buffer.  However, this may violate the normal hints set on other X
windows.

(fn DELTA &optional HORIZONTAL)" t)
(autoload 'exwm-layout-enlarge-window-horizontally "exwm-layout" "\
Make the selected window DELTA pixels wider.

See also `exwm-layout-enlarge-window'.

(fn DELTA)" t)
(autoload 'exwm-layout-shrink-window "exwm-layout" "\
Make the selected window DELTA pixels lower.

See also `exwm-layout-enlarge-window'.

(fn DELTA)" t)
(autoload 'exwm-layout-shrink-window-horizontally "exwm-layout" "\
Make the selected window DELTA pixels narrower.

See also `exwm-layout-enlarge-window'.

(fn DELTA)" t)
(autoload 'exwm-layout-hide-mode-line "exwm-layout" "\
Hide mode-line." t)
(autoload 'exwm-layout-show-mode-line "exwm-layout" "\
Show mode-line." t)
(autoload 'exwm-layout-toggle-mode-line "exwm-layout" "\
Toggle the display of mode-line." t)
(register-definition-prefixes "exwm-layout" '("exwm-layout-"))


;;; Generated autoloads from exwm-manage.el

(register-definition-prefixes "exwm-manage" '("exwm-manage-"))


;;; Generated autoloads from exwm-randr.el

(autoload 'exwm-randr-refresh "exwm-randr" "\
Refresh workspaces according to the updated RandR info." t)
(register-definition-prefixes "exwm-randr" '("exwm-randr-"))


;;; Generated autoloads from exwm-systemtray.el

(register-definition-prefixes "exwm-systemtray" '("exwm-systemtray-" "xcb:systemtray:-ClientMessage"))


;;; Generated autoloads from exwm-workspace.el

(autoload 'exwm-workspace--get-geometry "exwm-workspace" "\
Return the geometry of frame FRAME.

(fn FRAME)")
(autoload 'exwm-workspace--current-height "exwm-workspace" "\
Return the height of current workspace.")
(autoload 'exwm-workspace--minibuffer-own-frame-p "exwm-workspace" "\
Reports whether the minibuffer is displayed in its own frame.")
(autoload 'exwm-workspace-switch "exwm-workspace" "\
Switch to workspace INDEX (0-based).

Query for the index if not specified when called interactively.  Passing a
workspace frame as the first option or making use of the rest options are
for internal use only.

(fn FRAME-OR-INDEX &optional FORCE)" t)
(autoload 'exwm-workspace-switch-create "exwm-workspace" "\
Switch to workspace INDEX or creating it first if it does not exist yet.

Passing a workspace frame as the first option is for internal use only.

(fn FRAME-OR-INDEX)" t)
(autoload 'exwm-workspace-swap "exwm-workspace" "\
Interchange position of WORKSPACE1 with that of WORKSPACE2.

(fn WORKSPACE1 WORKSPACE2)" t)
(autoload 'exwm-workspace-move "exwm-workspace" "\
Move WORKSPACE to the NTH position.

When called interactively, prompt for a workspace and move current one just
before it.

(fn WORKSPACE NTH)" t)
(autoload 'exwm-workspace-add "exwm-workspace" "\
Add a workspace as the INDEX-th workspace, or the last one if INDEX is nil.

INDEX must not exceed the current number of workspaces.

(fn &optional INDEX)" t)
(autoload 'exwm-workspace-delete "exwm-workspace" "\
Delete the workspace FRAME-OR-INDEX.

(fn &optional FRAME-OR-INDEX)" t)
(autoload 'exwm-workspace-move-window "exwm-workspace" "\
Move window ID to workspace FRAME-OR-INDEX.

(fn FRAME-OR-INDEX &optional ID)" t)
(autoload 'exwm-workspace-switch-to-buffer "exwm-workspace" "\
Make the current Emacs window display another buffer.

(fn BUFFER-OR-NAME)" t)
(autoload 'exwm-workspace-attach-minibuffer "exwm-workspace" "\
Attach the minibuffer so that it always shows." t)
(autoload 'exwm-workspace-detach-minibuffer "exwm-workspace" "\
Detach the minibuffer so that it automatically hides." t)
(autoload 'exwm-workspace-toggle-minibuffer "exwm-workspace" "\
Attach the minibuffer if it's detached, or detach it if it's attached." t)
(register-definition-prefixes "exwm-workspace" '("exwm-workspace-"))


;;; Generated autoloads from exwm-xim.el

(register-definition-prefixes "exwm-xim" '("exwm-xim-"))

;;; End of scraped data

(provide 'exwm-autoloads)

;; Local Variables:
;; version-control: never
;; no-byte-compile: t
;; no-update-autoloads: t
;; no-native-compile: t
;; coding: utf-8-emacs-unix
;; End:

;;; exwm-autoloads.el ends here
